### ISSUE TITLE
error when trying to run safetyculture-exporter linux

### ISSUE THREAD

**Issue by dinzhd** [SafetyCulture/safetyculture-exporter#464]
**When trying to run the following command on a Linux server:**

./safetyculture-exporter configure

**Run into the following error:**

./safetyculture-exporter: /lib64/libc.so.6: version 'GLIBC_2.28' not found (required by ./safetyculture-exporter)
./safetyculture-exporter: /lib64/libc.so.6: version 'GLIBC_2.33' not found (required by ./safetyculture-exporter)
./safetyculture-exporter: /lib64/libc.so.6: version 'GLIBC_2.32' not found (required by ./safetyculture-exporter)
./safetyculture-exporter: /lib64/libc.so.6: version 'GLIBC_2.34' not found (required by ./safetyculture-exporter)

**Comment by MickStanciu** [comment]
> ./safetyculture-exporter configure

hi, are you able to compile the project yourself (we are using GO). Just for curiosity.

Our Mac/Windows builds are working fine. The Linux, due to so many flavours, it's hard to anticipate.

Our linux builds are based on `ubuntu-latest` and we are executing the following:

`sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config gcc-mingw-w64 zip`

`GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -v -ldflags "-s -w -X github.com/SafetyCulture/safetyculture-exporter/internal/app/version.version=${{ github.ref_name }}" -o safetyculture-exporter ./cmd/safetyculture-exporter/main.go`

**Comment by dinzhd** [comment]
Hey, i've not setup GO on my system yet, but if required then will get to it.
I should probably mention that the linux I'm using is Amazon Linux. I read somewhere that apparently these support only GLIBC 2.17 or sth.

**Comment by MickStanciu** [comment]
> I should probably mention that the linux I'm using is Amazon Linux. I read somewhere that apparently these support only GLIBC 2.17 or sth.

If you find a way to make it work, please let us know and we could update our build script to support more customers.

BTW: you can pass anything locally in `-X github.com/SafetyCulture/safetyculture-exporter/internal/app/version.version=${{ github.ref_name }}"`. Usually we put the latest version (GIT TAG)

**Comment by dinzhd** [comment]
Hey, I've managed to make it work by using your source code to compile for Amazon Linux 2. I'll attached the newly compiled executable here.
[SafetyCulture-Exporter_AL2.zip](https://github.com/SafetyCulture/safetyculture-exporter/files/14912843/SafetyCulture-Exporter_AL2.zip)

However I've come across another issue that seems to be related to Golang.

2024-04-09T02:35:25.581Z	ERROR	safetyculture-exporter	http request error	{"version": "4.18.0", "pid": 22958, "uid": 1002, "url": "https://api.safetyculture.io/training/v1/feed/training-course-progress?completion_status=COMPLETION_STATUS_COMPLETED&limit=1000", "status": "504 Gateway Timeout", "err": "invalid character 'e' looking for beginning of value"}

Not sure what it is but some context would be useful in trying to fix this.

**Comment by MickStanciu** [comment]
Hi, I will have a look at that
